version: "3.9"

services:
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: gatenjia_frontend
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
    env_file:
      - ../apps/frontend/.env
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: gatenjia_backend
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ../apps/backend:/app
      - /app/node_modules
    env_file:
      - ../apps/backend/.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: gatenjia_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
